INSERT INTO `conflines` (`name`, `value`) VALUES ('Active_Calls_Count',4);
INSERT INTO `acc_groups`(`id`,`name`) VALUES (1,'Accountant_Permissions');   
INSERT INTO `backups`   (`id`,`backuptime`,`comment`,`backuptype`) VALUES (1 ,'20110929151451','Komentaras','manual');
INSERT INTO `locations`(`id`,`name`) VALUES (2,'Location');
INSERT INTO `customrates`(`id`,`user_id`,`destinationgroup_id`) VALUES (1,3,1);
INSERT INTO `callerids`(`id`,`cli`,`device_id`,`description`,`added_at`,`banned`,`created_at`,`updated_at`,`ivr_id`,`comment`,`email_callback`) VALUES (  1 , 654  ,         5 ,''             ,'2011-10-01 13:36:59' ,      0 ,'2011-10-01 13:36:59','2011-10-01 13:36:59',      0 ,''         ,             0 );
INSERT INTO `groups`(`id`,`name`,`grouptype`) VALUES (2 ,'USERS GROUP','simple');
INSERT INTO `usergroups`(`id`,`user_id`,`group_id`,`gusertype`) VALUES (5 , 0 ,2 ,'user');
INSERT INTO `tariffs` (`id`, `name`, `purpose`, `owner_id`, `currency`) VALUES (6, 'test_tarrif', 'user_wholesale', 3, 'USD');
INSERT INTO `rates` (`id`, `tariff_id`, `destination_id`, `destinationgroup_id`) VALUES (503, 6, 2, NULL);
INSERT INTO `tariffs` (`id`, `name`, `purpose`, `owner_id`, `currency`) VALUES (7, 'test_tarrif_providers', 'provider', 3, 'USD');
INSERT INTO `devices` (`id`, `name`, `host`  , `secret`, `context` , `ipaddr`, `port`     , `regseconds`, `accountcode` , `callerid`    , `extension`, `voicemail_active`, `username`, `device_type`, `user_id`, `primary_did_id`, `works_not_logged`, `forward_to`, `record`, `transfer`, `disallow`, `allow`         , `deny`          , `permit`, `nat`, `qualify`, `fullcontact`, `canreinvite`, `devicegroup_id`, `dtmfmode`, `callgroup`, `pickupgroup`, `fromuser`, `fromdomain`, `trustrpid`, `sendrpid`, `insecure`, `progressinband`, `videosupport`, `location_id`                  , `description`, `istrunk`, `cid_from_dids`, `pin`, `tell_balance`, `tell_time`, `tell_rtime_when_left`, `repeat_rtime_every`, `t38pt_udptl`, `regserver`, `ani`, `promiscredir`, `timeout`, `process_sipchaninfo`, `temporary_id`, `allow_duplicate_calls`, `call_limit`, `faststart`, `h245tunneling`, `latency`, `grace_time`, `recording_to_email`, `recording_keep`, `recording_email`)
VALUES                (8   ,'108'  ,'dynamic','108'    ,'mor_local','0.0.0.0',0           ,1175892667   ,2              ,'\"108\" <108>','108'       ,0                  ,'108'      ,'IAX2'        ,-1        ,0               ,1                ,0                  ,0            ,'no'     ,'all'      ,'all'      ,'0.0.0.0/0.0.0.0','0.0.0.0/0.0.0.0','yes'    ,'yes' ,''        ,'no'          ,NULL          ,'rfc2833'        ,NULL       ,NULL        ,NULL          ,NULL       ,'no'         ,'no'        ,'no'       ,'never'    ,'no'             ,1              ,'Test Device for Resellers User',0             ,0         ,NULL            ,0     ,0              ,60          ,60                     ,'no'                 ,NULL          ,0           ,'no'  ,60             ,0         ,NULL                  ,0              ,0                       ,'yes'        ,'yes'       ,0               ,0         ,0            ,0                    ,NULL),
                      (9   ,'109'  ,'dynamic','109'    ,'mor_local','0.0.0.0',0           ,1175892667   ,2              ,'\"109\" <109>','109'       ,0                  ,'109'      ,'SIP'         ,1000      ,0               ,1                ,0                  ,0            ,'no'     ,'all'      ,'all'      ,'0.0.0.0/0.0.0.0','0.0.0.0/0.0.0.0','yes'    ,'yes' ,''        ,'no'          ,NULL          ,'rfc2833'        ,NULL       ,NULL        ,NULL          ,NULL       ,'no'         ,'no'        ,'no'       ,'never'    ,'no'             ,1              ,'Test Device for Accountant'    ,0             ,0         ,NULL            ,0     ,0              ,60          ,60                     ,'no'                 ,NULL          ,0           ,'no'  ,60             ,0         ,NULL                  ,0              ,0                       ,'yes'        ,'yes'       ,0               ,0         ,0            ,0                    ,NULL);
