INSERT INTO `tariffs` (`id`, `name`, `purpose`, `owner_id`, `currency`) VALUES
(11, 'Test Tariff', 'provider', 0, 'USD'),
(12, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(13, 'Test Tariff', 'provider', 0, 'USD'),
(14, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(15, 'Test Tariff', 'provider', 0, 'USD'),
(16, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(17, 'Test Tariff', 'provider', 0, 'USD'),
(18, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(19, 'Test Tariff', 'provider', 0, 'USD'),
(20, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(21, 'Test Tariff', 'provider', 0, 'USD'),
(22, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(23, 'Test Tariff', 'provider', 0, 'USD'),
(24, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(25, 'Test Tariff', 'provider', 0, 'USD'),
(26, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(27, 'Test Tariff', 'provider', 0, 'USD'),
(28, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(29, 'Test Tariff', 'provider', 0, 'USD'),
(30, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(31, 'Test Tariff', 'provider', 0, 'USD'),
(32, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(33, 'Test Tariff', 'provider', 0, 'USD'),
(34, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(35, 'Test Tariff', 'provider', 0, 'USD'),
(36, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(37, 'Test Tariff', 'provider', 0, 'USD'),
(38, 'Test Tariff for Users', 'user_wholesale', 0, 'USD'),
(39, 'Test Tariff', 'provider', 0, 'USD'),
(40, 'Test Tariff for Users', 'user_wholesale', 0, 'USD');