INSERT INTO `dial_peers` (`id`, `active`, `name`, `comment`, `dst_regexp`, `dst_deny_regexp`, `src_regexp`, `src_deny_regexp`, `weight`, `stop_hunting`, `minimal_rate_margin`, `tp_priority`) VALUES
(1, 0, 'Inactive Dial Peer', 'Percent 500 0.2USD', 'random', 'random', '', '', 500, 0, 0.200000000000000, 'percent'),
(2, 1, 'Active Dial Peer', 'Weight 111 1.7 USD', 'some regexp', 'some deny regexp', '', '', 111, 1, 1.700000000000000, 'weight');
INSERT INTO `devices` (`id`, `name`, `host`, `secret`, `context`, `ipaddr`, `port`, `regseconds`, `accountcode`, `callerid`, `extension`, `voicemail_active`, `username`, `device_type`, `user_id`, `primary_did_id`, `works_not_logged`, `forward_to`, `record`, `transfer`, `disallow`, `allow`, `deny`, `permit`, `nat`, `qualify`, `fullcontact`, `canreinvite`, `devicegroup_id`, `dtmfmode`, `callgroup`, `pickupgroup`, `fromuser`, `fromdomain`, `trustrpid`, `sendrpid`, `insecure`, `progressinband`, `videosupport`, `location_id`, `description`, `istrunk`, `cid_from_dids`, `pin`, `tell_balance`, `tell_time`, `tell_rtime_when_left`, `repeat_rtime_every`, `t38pt_udptl`, `regserver`, `ani`, `promiscredir`, `timeout`, `process_sipchaninfo`, `temporary_id`, `allow_duplicate_calls`, `call_limit`, `lastms`, `faststart`, `h245tunneling`, `latency`, `grace_time`, `recording_to_email`, `recording_keep`, `recording_email`, `record_forced`, `fake_ring`, `save_call_log`, `mailbox`, `server_id`, `enable_mwi`, `authuser`, `requirecalltoken`, `language`, `use_ani_for_cli`, `calleridpres`, `change_failed_code_to`, `reg_status`, `max_timeout`, `forward_did_id`, `anti_resale_auto_answer`, `qf_tell_balance`, `qf_tell_time`, `time_limit_per_day`, `control_callerid_by_cids`, `callerid_advanced_control`, `transport`, `subscribemwi`, `encryption`, `block_callerid`, `tell_rate`, `trunk`, `proxy_port`, `cps_call_limit`, `cps_period`, `timerb`, `callerid_number_pool_id`, `op`, `op_active`, `op_tech_prefix`, `op_routing_algorithm`, `op_routing_group_id`, `op_tariff_id`, `op_capacity`, `op_src_regexp`, `op_src_deny_regexp`, `tp`, `tp_active`, `tp_tech_prefix`, `tp_tariff_id`, `tp_capacity`, `tp_src_regexp`, `tp_src_deny_regexp`, `defaultuser`, `useragent`, `type`, `md5secret`, `remotesecret`, `directmedia`, `useclientcode`, `setvar`, `amaflags`, `callcounter`, `busylevel`, `allowoverlap`, `allowsubscribe`, `maxcallbitrate`, `rfc2833compensate`, `session-timers`, `session-expires`, `session-minse`, `session-refresher`, `t38pt_usertpsource`, `regexten`, `defaultip`, `rtptimeout`, `rtpholdtimeout`, `outboundproxy`, `callbackextension`, `timert1`, `qualifyfreq`, `constantssrc`, `contactpermit`, `contactdeny`, `usereqphone`, `textsupport`, `faxdetect`, `buggymwi`, `auth`, `fullname`, `trunkname`, `cid_number`, `callingpres`, `mohinterpret`, `mohsuggest`, `parkinglot`, `hasvoicemail`, `vmexten`, `autoframing`, `rtpkeepalive`, `call-limit`, `g726nonstandard`, `ignoresdpversion`, `allowtransfer`, `dynamic`) VALUES
(18, '118', 'dynamic', '1181dfgh', 'mor_local', '0.0.0.0', 5060, 1175892667, 18, '"118" <118>', '118', 0, '118', 'SIP', 2, 0, 1, 0, 0, 'no', 'all', 'all', '0.0.0.0/0.0.0.0', '0.0.0.0/0.0.0.0', 'yes', '500', '', 'no', NULL, 'rfc2833', NULL, NULL, NULL, NULL, 'no', 'no', NULL, 'never', 'no', 1, '', 0, 0, '', 0, 0, 0, 0, 'no', NULL, 0, 'no', 60, 0, NULL, 0, 0, 0, 'yes', 'yes', 0.000000000000000, 0, 0, 0, '', 0, 0, 0, '', 1, 0, '', 'no', 'en', 0, '', 0, NULL, 0, -1, 0, 0, 0, 0, 0, 0, 'udp', 'no', 'no', 0, 0, 'no', 5060, 0, 0, 6400, 0, 0, 0, '', 'lcr', 0, 0, 500, '', '', 1, 1, '5', 1, 500, '8605646464', '464676416456', '118', NULL, 'friend', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(46, '146', 'dynamic', '146646361464', 'mor_local', '0.0.0.0', 5060, 1175892667, 46, '"146" <146>', '146', 0, '146', 'SIP', 2, 0, 1, 0, 0, 'no', 'all', 'all', '0.0.0.0/0.0.0.0', '0.0.0.0/0.0.0.0', 'yes', '500', '', 'no', NULL, 'rfc2833', NULL, NULL, NULL, NULL, 'no', 'no', NULL, 'never', 'no', 1, '', 0, 0, '', 0, 0, 0, 0, 'no', NULL, 0, 'no', 60, 0, NULL, 0, 0, 0, 'yes', 'yes', 0.000000000000000, 0, 0, 0, '', 0, 0, 0, '', 1, 0, '', 'no', 'en', 0, '', 0, NULL, 0, -1, 0, 0, 0, 0, 0, 0, 'udp', 'no', 'no', 0, 0, 'no', 5060, 0, 0, 6400, 0, 0, 0, '', 'lcr', 0, 0, 500, '', '', 1, 1, '98', 2, 500, '64646764164', '1654674146', '146', NULL, 'friend', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `dpeer_tpoints` (`id`, `dial_peer_id`, `device_id`, `tp_percent`, `tp_weight`, `active`) VALUES
(1, 1, 18, 100, 1, 1),
(2, 1, 46, 100, 1, 1),
(3, 2, 18, 100, 1, 1),
(4, 2, 46, 100, 1, 1);
